package initactor
	
/* 
DO NOT EDIT THIS FILE BY HAND

This file was generated by "github.com/filecoin-project/go-filecoin/encoding/gen" 
*/

import (
	"github.com/filecoin-project/go-filecoin/encoding"
)

func init() {
    encoding.RegisterIpldCborType(State{})
}

//
// Encoding/Decoding impls for State 
// 
	