package paymentbroker

/*
DO NOT EDIT THIS FILE BY HAND

This file was generated by "github.com/filecoin-project/go-filecoin/internal/pkg/encoding/gen"
*/

import (
	"github.com/filecoin-project/go-filecoin/internal/pkg/encoding"
)

func init() {
	encoding.RegisterIpldCborType(PaymentChannel{})
}

//
// Encoding/Decoding impls for PaymentChannel
//
