// Code generated by github.com/filecoin-project/venus/venus-devtool/state-type-gen. DO NOT EDIT.
package types

import (
	"github.com/filecoin-project/venus/venus-shared/actors/types"
)

var (
	EmptyInt = types.EmptyInt
)

type (
	BigInt = types.BigInt
)

var (
	BigAdd        = types.BigAdd
	BigCmp        = types.BigCmp
	BigDiv        = types.BigDiv
	BigDivFloat   = types.BigDivFloat
	BigFromBytes  = types.BigFromBytes
	BigFromString = types.BigFromString
	BigMod        = types.BigMod
	BigMul        = types.BigMul
	BigSub        = types.BigSub
	NewInt        = types.NewInt
)
