// Code generated by github.com/filecoin-project/venus/venus-devtool/state-type-gen. DO NOT EDIT.
package types

import (
	"github.com/filecoin-project/venus/venus-shared/actors/types"
)

const (
	Eip1559TxType = types.Eip1559TxType
)

type (
	EthTx     = types.EthTx
	EthTxArgs = types.EthTxArgs
)

var (
	EthTxArgsFromUnsignedEthMessage = types.EthTxArgsFromUnsignedEthMessage
	EthTxFromSignedEthMessage       = types.EthTxFromSignedEthMessage
	ParseEthTxArgs                  = types.ParseEthTxArgs
	RecoverSignature                = types.RecoverSignature
)
