// Code generated by github.com/filecoin-project/venus/venus-devtool/state-type-gen. DO NOT EDIT.
package types

import (
	"github.com/filecoin-project/venus/venus-shared/actors/types"
)

type (
	Eth1559TxArgs = types.Eth1559TxArgs
)

var (
	Eth1559TxArgsFromUnsignedFilecoinMessage = types.Eth1559TxArgsFromUnsignedFilecoinMessage
)
