// Code generated by github.com/filecoin-project/venus/venus-devtool/state-type-gen. DO NOT EDIT.
package types

import (
	"github.com/filecoin-project/venus/venus-shared/actors/types"
)

const (
	MessageVersion = types.MessageVersion
)

type (
	ChainMsg = types.ChainMsg
)
type (
	Message = types.Message
)

var (
	DecodeMessage = types.DecodeMessage
)
