// Code generated by github.com/filecoin-project/venus/venus-devtool/state-type-gen. DO NOT EDIT.
package types

import (
	"github.com/filecoin-project/go-state-types/builtin/v8/paych"
	"github.com/filecoin-project/go-state-types/builtin/v9/market"
	"github.com/filecoin-project/go-state-types/builtin/v9/miner"
	"github.com/filecoin-project/go-state-types/builtin/v9/verifreg"
)

////////// market //////////
type ActivateDealsParams = market.ActivateDealsParams
type ActivateDealsResult = market.ActivateDealsResult
type ClientDealProposal = market.ClientDealProposal
type ComputeDataCommitmentParams = market.ComputeDataCommitmentParams
type ComputeDataCommitmentReturn = market.ComputeDataCommitmentReturn
type DealArray = market.DealArray
type DealLabel = market.DealLabel
type DealProposal = market.DealProposal
type DealSpaces = market.DealSpaces
type DealState = market.DealState
type OnMinerSectorsTerminateParams = market.OnMinerSectorsTerminateParams
type PublishStorageDealsParams = market.PublishStorageDealsParams
type PublishStorageDealsReturn = market.PublishStorageDealsReturn
type SectorDataSpec = market.SectorDataSpec
type SectorDealData = market.SectorDealData
type SectorDeals = market.SectorDeals
type SetMultimap = market.SetMultimap
type VerifiedDealInfo = market.VerifiedDealInfo
type VerifyDealsForActivationParams = market.VerifyDealsForActivationParams
type VerifyDealsForActivationReturn = market.VerifyDealsForActivationReturn
type MarketWithdrawBalanceParams = market.WithdrawBalanceParams

var AsDealProposalArray = market.AsDealProposalArray
var AsSetMultimap = market.AsSetMultimap
var DealClientCollateralBounds = market.DealClientCollateralBounds
var DealDurationBounds = market.DealDurationBounds
var DealPricePerEpochBounds = market.DealPricePerEpochBounds
var DealProviderCollateralBounds = market.DealProviderCollateralBounds
var DealWeight = market.DealWeight
var MakeEmptySetMultimap = market.MakeEmptySetMultimap
var NewLabelFromBytes = market.NewLabelFromBytes
var NewLabelFromString = market.NewLabelFromString
var StoreEmptySetMultimap = market.StoreEmptySetMultimap
var ValidateDealsForActivation = market.ValidateDealsForActivation

const DealMaxLabelSize = market.DealMaxLabelSize
const EpochUndefined = market.EpochUndefined
const ProposalsAmtBitwidth = market.ProposalsAmtBitwidth
const StatesAmtBitwidth = market.StatesAmtBitwidth

////////// miner //////////
type ActiveBeneficiary = miner.ActiveBeneficiary
type ApplyRewardParams = miner.ApplyRewardParams
type BeneficiaryTerm = miner.BeneficiaryTerm
type ChangeBeneficiaryParams = miner.ChangeBeneficiaryParams
type ChangeMultiaddrsParams = miner.ChangeMultiaddrsParams
type ChangePeerIDParams = miner.ChangePeerIDParams
type ChangeWorkerAddressParams = miner.ChangeWorkerAddressParams
type CheckSectorProvenParams = miner.CheckSectorProvenParams
type CompactPartitionsParams = miner.CompactPartitionsParams
type CompactSectorNumbersParams = miner.CompactSectorNumbersParams
type ConfirmSectorProofsParams = miner.ConfirmSectorProofsParams
type CronEventPayload = miner.CronEventPayload
type CronEventType = miner.CronEventType
type Deadlines = miner.Deadlines
type DeclareFaultsParams = miner.DeclareFaultsParams
type DeclareFaultsRecoveredParams = miner.DeclareFaultsRecoveredParams
type DeferredCronEventParams = miner.DeferredCronEventParams
type DisputeWindowedPoStParams = miner.DisputeWindowedPoStParams
type ExpirationExtension = miner.ExpirationExtension
type ExpirationExtension2 = miner.ExpirationExtension2
type ExpirationQueue = miner.ExpirationQueue
type ExpirationSet = miner.ExpirationSet
type ExtendSectorExpiration2Params = miner.ExtendSectorExpiration2Params
type ExtendSectorExpirationParams = miner.ExtendSectorExpirationParams
type FaultDeclaration = miner.FaultDeclaration
type GetBeneficiaryReturn = miner.GetBeneficiaryReturn
type GetControlAddressesReturn = miner.GetControlAddressesReturn
type PartitionKey = miner.PartitionKey
type PendingBeneficiaryChange = miner.PendingBeneficiaryChange
type PoStPartition = miner.PoStPartition
type PowerPair = miner.PowerPair
type PreCommitSectorBatchParams = miner.PreCommitSectorBatchParams
type PreCommitSectorBatchParams2 = miner.PreCommitSectorBatchParams2
type PreCommitSectorParams = miner.PreCommitSectorParams
type ProveCommitAggregateParams = miner.ProveCommitAggregateParams
type ProveCommitSectorParams = miner.ProveCommitSectorParams
type ProveReplicaUpdatesParams = miner.ProveReplicaUpdatesParams
type ProveReplicaUpdatesParams2 = miner.ProveReplicaUpdatesParams2
type RecoveryDeclaration = miner.RecoveryDeclaration
type ReplicaUpdate = miner.ReplicaUpdate
type ReplicaUpdate2 = miner.ReplicaUpdate2
type ReportConsensusFaultParams = miner.ReportConsensusFaultParams
type SectorClaim = miner.SectorClaim
type SectorOnChainInfo = miner.SectorOnChainInfo
type SectorPreCommitInfo = miner.SectorPreCommitInfo
type SectorPreCommitOnChainInfo = miner.SectorPreCommitOnChainInfo
type Sectors = miner.Sectors
type SubmitWindowedPoStParams = miner.SubmitWindowedPoStParams
type TerminateSectorsParams = miner.TerminateSectorsParams
type TerminateSectorsReturn = miner.TerminateSectorsReturn
type TerminationDeclaration = miner.TerminationDeclaration
type VestSpec = miner.VestSpec
type VestingFund = miner.VestingFund
type VestingFunds = miner.VestingFunds
type WindowedPoSt = miner.WindowedPoSt
type MinerWithdrawBalanceParams = miner.WithdrawBalanceParams
type WorkerKeyChange = miner.WorkerKeyChange

var AggregatePreCommitNetworkFee = miner.AggregatePreCommitNetworkFee
var AggregateProveCommitNetworkFee = miner.AggregateProveCommitNetworkFee
var ConstructDeadline = miner.ConstructDeadline
var ConstructDeadlines = miner.ConstructDeadlines
var ConstructVestingFunds = miner.ConstructVestingFunds
var ExpectedRewardForPower = miner.ExpectedRewardForPower
var ExpectedRewardForPowerClampedAtAttoFIL = miner.ExpectedRewardForPowerClampedAtAttoFIL
var FindSector = miner.FindSector
var InitialPledgeForPower = miner.InitialPledgeForPower
var LoadExpirationQueue = miner.LoadExpirationQueue
var LoadSectors = miner.LoadSectors
var NewDeadlineInfo = miner.NewDeadlineInfo
var NewPowerPair = miner.NewPowerPair
var NewPowerPairZero = miner.NewPowerPairZero
var PreCommitDepositForPower = miner.PreCommitDepositForPower
var QAPowerForSector = miner.QAPowerForSector
var QAPowerForWeight = miner.QAPowerForWeight
var QAPowerMax = miner.QAPowerMax
var QualityForWeight = miner.QualityForWeight
var QuantSpecForDeadline = miner.QuantSpecForDeadline
var SectorKey = miner.SectorKey

const AddressedPartitionsMax = miner.AddressedPartitionsMax
const AddressedSectorsMax = miner.AddressedSectorsMax
const ChainFinality = miner.ChainFinality
const CronEventProcessEarlyTerminations = miner.CronEventProcessEarlyTerminations
const CronEventProvingDeadline = miner.CronEventProvingDeadline
const CronEventWorkerKeyChange = miner.CronEventWorkerKeyChange
const DeadlineExpirationAmtBitwidth = miner.DeadlineExpirationAmtBitwidth
const DeadlineOptimisticPoStSubmissionsAmtBitwidth = miner.DeadlineOptimisticPoStSubmissionsAmtBitwidth
const DeadlinePartitionsAmtBitwidth = miner.DeadlinePartitionsAmtBitwidth
const DeclarationsMax = miner.DeclarationsMax
const FaultDeclarationCutoff = miner.FaultDeclarationCutoff
const MaxAggregateProofSize = miner.MaxAggregateProofSize
const MaxAggregatedSectors = miner.MaxAggregatedSectors
const MaxPartitionsPerDeadline = miner.MaxPartitionsPerDeadline
const MaxSectorExpirationExtension = miner.MaxSectorExpirationExtension
const MinAggregatedSectors = miner.MinAggregatedSectors
const MinSectorExpiration = miner.MinSectorExpiration
const PartitionEarlyTerminationArrayAmtBitwidth = miner.PartitionEarlyTerminationArrayAmtBitwidth
const PartitionExpirationAmtBitwidth = miner.PartitionExpirationAmtBitwidth
const PreCommitSectorBatchMaxSize = miner.PreCommitSectorBatchMaxSize
const PrecommitCleanUpAmtBitwidth = miner.PrecommitCleanUpAmtBitwidth
const ProveReplicaUpdatesMaxSize = miner.ProveReplicaUpdatesMaxSize
const SectorsAmtBitwidth = miner.SectorsAmtBitwidth
const WPoStChallengeLookback = miner.WPoStChallengeLookback
const WPoStPeriodDeadlines = miner.WPoStPeriodDeadlines
const WorkerKeyChangeDelay = miner.WorkerKeyChangeDelay

////////// paych //////////
type ConstructorParams = paych.ConstructorParams
type LaneState = paych.LaneState
type Merge = paych.Merge
type ModVerifyParams = paych.ModVerifyParams
type SignedVoucher = paych.SignedVoucher
type UpdateChannelStateParams = paych.UpdateChannelStateParams

const LaneStatesAmtBitwidth = paych.LaneStatesAmtBitwidth
const SettleDelay = paych.SettleDelay

////////// verifreg //////////
type AddVerifiedClientParams = verifreg.AddVerifiedClientParams
type AddVerifierParams = verifreg.AddVerifierParams
type Allocation = verifreg.Allocation
type AllocationId = verifreg.AllocationId
type AllocationRequest = verifreg.AllocationRequest
type AllocationRequests = verifreg.AllocationRequests
type AllocationsResponse = verifreg.AllocationsResponse
type BatchReturn = verifreg.BatchReturn
type Claim = verifreg.Claim
type ClaimAllocationsParams = verifreg.ClaimAllocationsParams
type ClaimAllocationsReturn = verifreg.ClaimAllocationsReturn
type ClaimExtensionRequest = verifreg.ClaimExtensionRequest
type ClaimId = verifreg.ClaimId
type ClaimTerm = verifreg.ClaimTerm
type ExtendClaimTermsParams = verifreg.ExtendClaimTermsParams
type ExtendClaimTermsReturn = verifreg.ExtendClaimTermsReturn
type FailCode = verifreg.FailCode
type GetClaimsParams = verifreg.GetClaimsParams
type GetClaimsReturn = verifreg.GetClaimsReturn
type ReceiverType = verifreg.ReceiverType
type RemoveDataCapParams = verifreg.RemoveDataCapParams
type RemoveDataCapProposal = verifreg.RemoveDataCapProposal
type RemoveDataCapRequest = verifreg.RemoveDataCapRequest
type RemoveDataCapReturn = verifreg.RemoveDataCapReturn
type RemoveExpiredAllocationsParams = verifreg.RemoveExpiredAllocationsParams
type RemoveExpiredAllocationsReturn = verifreg.RemoveExpiredAllocationsReturn
type RemoveExpiredClaimsParams = verifreg.RemoveExpiredClaimsParams
type RemoveExpiredClaimsReturn = verifreg.RemoveExpiredClaimsReturn
type RestoreBytesParams = verifreg.RestoreBytesParams
type RmDcProposalID = verifreg.RmDcProposalID
type SectorAllocationClaim = verifreg.SectorAllocationClaim
type UniversalReceiverParams = verifreg.UniversalReceiverParams
type UseBytesParams = verifreg.UseBytesParams

const EndOfLifeClaimDropPeriod = verifreg.EndOfLifeClaimDropPeriod
const MaximumVerifiedAllocationExpiration = verifreg.MaximumVerifiedAllocationExpiration
const MaximumVerifiedAllocationTerm = verifreg.MaximumVerifiedAllocationTerm
const MinimumVerifiedAllocationSize = verifreg.MinimumVerifiedAllocationSize
const MinimumVerifiedAllocationTerm = verifreg.MinimumVerifiedAllocationTerm
const NoAllocationID = verifreg.NoAllocationID
const SignatureDomainSeparation_RemoveDataCap = verifreg.SignatureDomainSeparation_RemoveDataCap
