// Code generated by github.com/filecoin-project/venus/venus-devtool/state-type-gen. DO NOT EDIT.
package types

import (
	"github.com/filecoin-project/go-state-types/builtin/v8/paych"
	"github.com/filecoin-project/go-state-types/builtin/v9/market"
	"github.com/filecoin-project/go-state-types/builtin/v9/miner"
	"github.com/filecoin-project/go-state-types/builtin/v9/verifreg"
)

////////// market //////////

const (
	DealMaxLabelSize     = market.DealMaxLabelSize
	EpochUndefined       = market.EpochUndefined
	ProposalsAmtBitwidth = market.ProposalsAmtBitwidth
	StatesAmtBitwidth    = market.StatesAmtBitwidth
)

type (
	ActivateDealsParams            = market.ActivateDealsParams
	ActivateDealsResult            = market.ActivateDealsResult
	ClientDealProposal             = market.ClientDealProposal
	ComputeDataCommitmentParams    = market.ComputeDataCommitmentParams
	ComputeDataCommitmentReturn    = market.ComputeDataCommitmentReturn
	DealArray                      = market.DealArray
	DealLabel                      = market.DealLabel
	DealProposal                   = market.DealProposal
	DealSpaces                     = market.DealSpaces
	DealState                      = market.DealState
	OnMinerSectorsTerminateParams  = market.OnMinerSectorsTerminateParams
	PublishStorageDealsParams      = market.PublishStorageDealsParams
	PublishStorageDealsReturn      = market.PublishStorageDealsReturn
	SectorDataSpec                 = market.SectorDataSpec
	SectorDealData                 = market.SectorDealData
	SectorDeals                    = market.SectorDeals
	SetMultimap                    = market.SetMultimap
	VerifiedDealInfo               = market.VerifiedDealInfo
	VerifyDealsForActivationParams = market.VerifyDealsForActivationParams
	VerifyDealsForActivationReturn = market.VerifyDealsForActivationReturn
	MarketWithdrawBalanceParams    = market.WithdrawBalanceParams
)

var (
	AsDealProposalArray          = market.AsDealProposalArray
	AsSetMultimap                = market.AsSetMultimap
	DealClientCollateralBounds   = market.DealClientCollateralBounds
	DealDurationBounds           = market.DealDurationBounds
	DealPricePerEpochBounds      = market.DealPricePerEpochBounds
	DealProviderCollateralBounds = market.DealProviderCollateralBounds
	DealWeight                   = market.DealWeight
	MakeEmptySetMultimap         = market.MakeEmptySetMultimap
	NewLabelFromBytes            = market.NewLabelFromBytes
	NewLabelFromString           = market.NewLabelFromString
	StoreEmptySetMultimap        = market.StoreEmptySetMultimap
	ValidateDealsForActivation   = market.ValidateDealsForActivation
)

////////// miner //////////

const (
	AddressedPartitionsMax                       = miner.AddressedPartitionsMax
	AddressedSectorsMax                          = miner.AddressedSectorsMax
	ChainFinality                                = miner.ChainFinality
	CronEventProcessEarlyTerminations            = miner.CronEventProcessEarlyTerminations
	CronEventProvingDeadline                     = miner.CronEventProvingDeadline
	CronEventWorkerKeyChange                     = miner.CronEventWorkerKeyChange
	DeadlineExpirationAmtBitwidth                = miner.DeadlineExpirationAmtBitwidth
	DeadlineOptimisticPoStSubmissionsAmtBitwidth = miner.DeadlineOptimisticPoStSubmissionsAmtBitwidth
	DeadlinePartitionsAmtBitwidth                = miner.DeadlinePartitionsAmtBitwidth
	DeclarationsMax                              = miner.DeclarationsMax
	FaultDeclarationCutoff                       = miner.FaultDeclarationCutoff
	MaxAggregateProofSize                        = miner.MaxAggregateProofSize
	MaxAggregatedSectors                         = miner.MaxAggregatedSectors
	MaxPartitionsPerDeadline                     = miner.MaxPartitionsPerDeadline
	MaxSectorExpirationExtension                 = miner.MaxSectorExpirationExtension
	MinAggregatedSectors                         = miner.MinAggregatedSectors
	MinSectorExpiration                          = miner.MinSectorExpiration
	PartitionEarlyTerminationArrayAmtBitwidth    = miner.PartitionEarlyTerminationArrayAmtBitwidth
	PartitionExpirationAmtBitwidth               = miner.PartitionExpirationAmtBitwidth
	PreCommitSectorBatchMaxSize                  = miner.PreCommitSectorBatchMaxSize
	PrecommitCleanUpAmtBitwidth                  = miner.PrecommitCleanUpAmtBitwidth
	ProveReplicaUpdatesMaxSize                   = miner.ProveReplicaUpdatesMaxSize
	SectorsAmtBitwidth                           = miner.SectorsAmtBitwidth
	WPoStChallengeLookback                       = miner.WPoStChallengeLookback
	WPoStPeriodDeadlines                         = miner.WPoStPeriodDeadlines
	WorkerKeyChangeDelay                         = miner.WorkerKeyChangeDelay
)

type (
	ActiveBeneficiary             = miner.ActiveBeneficiary
	ApplyRewardParams             = miner.ApplyRewardParams
	BeneficiaryTerm               = miner.BeneficiaryTerm
	ChangeBeneficiaryParams       = miner.ChangeBeneficiaryParams
	ChangeMultiaddrsParams        = miner.ChangeMultiaddrsParams
	ChangePeerIDParams            = miner.ChangePeerIDParams
	ChangeWorkerAddressParams     = miner.ChangeWorkerAddressParams
	CheckSectorProvenParams       = miner.CheckSectorProvenParams
	CompactPartitionsParams       = miner.CompactPartitionsParams
	CompactSectorNumbersParams    = miner.CompactSectorNumbersParams
	ConfirmSectorProofsParams     = miner.ConfirmSectorProofsParams
	CronEventPayload              = miner.CronEventPayload
	CronEventType                 = miner.CronEventType
	Deadlines                     = miner.Deadlines
	DeclareFaultsParams           = miner.DeclareFaultsParams
	DeclareFaultsRecoveredParams  = miner.DeclareFaultsRecoveredParams
	DeferredCronEventParams       = miner.DeferredCronEventParams
	DisputeWindowedPoStParams     = miner.DisputeWindowedPoStParams
	ExpirationExtension           = miner.ExpirationExtension
	ExpirationExtension2          = miner.ExpirationExtension2
	ExpirationQueue               = miner.ExpirationQueue
	ExpirationSet                 = miner.ExpirationSet
	ExtendSectorExpiration2Params = miner.ExtendSectorExpiration2Params
	ExtendSectorExpirationParams  = miner.ExtendSectorExpirationParams
	FaultDeclaration              = miner.FaultDeclaration
	GetBeneficiaryReturn          = miner.GetBeneficiaryReturn
	GetControlAddressesReturn     = miner.GetControlAddressesReturn
	PartitionKey                  = miner.PartitionKey
	PendingBeneficiaryChange      = miner.PendingBeneficiaryChange
	PoStPartition                 = miner.PoStPartition
	PowerPair                     = miner.PowerPair
	PreCommitSectorBatchParams    = miner.PreCommitSectorBatchParams
	PreCommitSectorBatchParams2   = miner.PreCommitSectorBatchParams2
	PreCommitSectorParams         = miner.PreCommitSectorParams
	ProveCommitAggregateParams    = miner.ProveCommitAggregateParams
	ProveCommitSectorParams       = miner.ProveCommitSectorParams
	ProveReplicaUpdatesParams     = miner.ProveReplicaUpdatesParams
	ProveReplicaUpdatesParams2    = miner.ProveReplicaUpdatesParams2
	RecoveryDeclaration           = miner.RecoveryDeclaration
	ReplicaUpdate                 = miner.ReplicaUpdate
	ReplicaUpdate2                = miner.ReplicaUpdate2
	ReportConsensusFaultParams    = miner.ReportConsensusFaultParams
	SectorClaim                   = miner.SectorClaim
	SectorOnChainInfo             = miner.SectorOnChainInfo
	SectorPreCommitInfo           = miner.SectorPreCommitInfo
	SectorPreCommitOnChainInfo    = miner.SectorPreCommitOnChainInfo
	Sectors                       = miner.Sectors
	SubmitWindowedPoStParams      = miner.SubmitWindowedPoStParams
	TerminateSectorsParams        = miner.TerminateSectorsParams
	TerminateSectorsReturn        = miner.TerminateSectorsReturn
	TerminationDeclaration        = miner.TerminationDeclaration
	VestSpec                      = miner.VestSpec
	VestingFund                   = miner.VestingFund
	VestingFunds                  = miner.VestingFunds
	WindowedPoSt                  = miner.WindowedPoSt
	MinerWithdrawBalanceParams    = miner.WithdrawBalanceParams
	WorkerKeyChange               = miner.WorkerKeyChange
)

var (
	AggregatePreCommitNetworkFee           = miner.AggregatePreCommitNetworkFee
	AggregateProveCommitNetworkFee         = miner.AggregateProveCommitNetworkFee
	ConstructDeadline                      = miner.ConstructDeadline
	ConstructDeadlines                     = miner.ConstructDeadlines
	ConstructVestingFunds                  = miner.ConstructVestingFunds
	ExpectedRewardForPower                 = miner.ExpectedRewardForPower
	ExpectedRewardForPowerClampedAtAttoFIL = miner.ExpectedRewardForPowerClampedAtAttoFIL
	FindSector                             = miner.FindSector
	InitialPledgeForPower                  = miner.InitialPledgeForPower
	LoadExpirationQueue                    = miner.LoadExpirationQueue
	LoadSectors                            = miner.LoadSectors
	NewDeadlineInfo                        = miner.NewDeadlineInfo
	NewPowerPair                           = miner.NewPowerPair
	NewPowerPairZero                       = miner.NewPowerPairZero
	PreCommitDepositForPower               = miner.PreCommitDepositForPower
	QAPowerForSector                       = miner.QAPowerForSector
	QAPowerForWeight                       = miner.QAPowerForWeight
	QAPowerMax                             = miner.QAPowerMax
	QualityForWeight                       = miner.QualityForWeight
	QuantSpecForDeadline                   = miner.QuantSpecForDeadline
	SectorKey                              = miner.SectorKey
)

////////// paych //////////

const (
	LaneStatesAmtBitwidth = paych.LaneStatesAmtBitwidth
	SettleDelay           = paych.SettleDelay
)

type (
	ConstructorParams        = paych.ConstructorParams
	LaneState                = paych.LaneState
	Merge                    = paych.Merge
	ModVerifyParams          = paych.ModVerifyParams
	SignedVoucher            = paych.SignedVoucher
	UpdateChannelStateParams = paych.UpdateChannelStateParams
)

////////// verifreg //////////

const (
	EndOfLifeClaimDropPeriod                = verifreg.EndOfLifeClaimDropPeriod
	MaximumVerifiedAllocationExpiration     = verifreg.MaximumVerifiedAllocationExpiration
	MaximumVerifiedAllocationTerm           = verifreg.MaximumVerifiedAllocationTerm
	MinimumVerifiedAllocationSize           = verifreg.MinimumVerifiedAllocationSize
	MinimumVerifiedAllocationTerm           = verifreg.MinimumVerifiedAllocationTerm
	NoAllocationID                          = verifreg.NoAllocationID
	SignatureDomainSeparation_RemoveDataCap = verifreg.SignatureDomainSeparation_RemoveDataCap
)

type (
	AddVerifiedClientParams        = verifreg.AddVerifiedClientParams
	AddVerifierParams              = verifreg.AddVerifierParams
	Allocation                     = verifreg.Allocation
	AllocationId                   = verifreg.AllocationId
	AllocationRequest              = verifreg.AllocationRequest
	AllocationRequests             = verifreg.AllocationRequests
	AllocationsResponse            = verifreg.AllocationsResponse
	BatchReturn                    = verifreg.BatchReturn
	Claim                          = verifreg.Claim
	ClaimAllocationsParams         = verifreg.ClaimAllocationsParams
	ClaimAllocationsReturn         = verifreg.ClaimAllocationsReturn
	ClaimExtensionRequest          = verifreg.ClaimExtensionRequest
	ClaimId                        = verifreg.ClaimId
	ClaimTerm                      = verifreg.ClaimTerm
	ExtendClaimTermsParams         = verifreg.ExtendClaimTermsParams
	ExtendClaimTermsReturn         = verifreg.ExtendClaimTermsReturn
	FailCode                       = verifreg.FailCode
	GetClaimsParams                = verifreg.GetClaimsParams
	GetClaimsReturn                = verifreg.GetClaimsReturn
	ReceiverType                   = verifreg.ReceiverType
	RemoveDataCapParams            = verifreg.RemoveDataCapParams
	RemoveDataCapProposal          = verifreg.RemoveDataCapProposal
	RemoveDataCapRequest           = verifreg.RemoveDataCapRequest
	RemoveDataCapReturn            = verifreg.RemoveDataCapReturn
	RemoveExpiredAllocationsParams = verifreg.RemoveExpiredAllocationsParams
	RemoveExpiredAllocationsReturn = verifreg.RemoveExpiredAllocationsReturn
	RemoveExpiredClaimsParams      = verifreg.RemoveExpiredClaimsParams
	RemoveExpiredClaimsReturn      = verifreg.RemoveExpiredClaimsReturn
	RestoreBytesParams             = verifreg.RestoreBytesParams
	RmDcProposalID                 = verifreg.RmDcProposalID
	SectorAllocationClaim          = verifreg.SectorAllocationClaim
	UniversalReceiverParams        = verifreg.UniversalReceiverParams
	UseBytesParams                 = verifreg.UseBytesParams
)
