// Code generated by github.com/filecoin-project/venus/venus-devtool/api-gen. DO NOT EDIT.
package market

import (
	"context"
	"net/http"

	"github.com/filecoin-project/go-jsonrpc"

	"github.com/filecoin-project/venus/venus-shared/api"
)

// NewIMarketRPC creates a new httpparse jsonrpc remotecli.
func NewIMarketRPC(ctx context.Context, addr string, requestHeader http.Header, opts ...jsonrpc.Option) (IMarket, jsonrpc.ClientCloser, error) {
	if requestHeader == nil {
		requestHeader = http.Header{}
	}
	requestHeader.Set(api.VenusAPINamespaceHeader, "market.IMarket")

	var res IMarketStruct
	closer, err := jsonrpc.NewMergeClient(ctx, addr, "VENUS_MARKET", api.GetInternalStructs(&res), requestHeader, opts...)

	return &res, closer, err
}
