package actor

/*
DO NOT EDIT THIS FILE BY HAND

This file was generated by "github.com/filecoin-project/go-filecoin/internal/pkg/encoding/gen"
*/

import (
	"github.com/filecoin-project/go-filecoin/internal/pkg/encoding"
)

func init() {
	encoding.RegisterIpldCborType(Actor{})
}

//
// Encoding/Decoding impls for Actor
//

//
// Encoding/Decoding impls for FakeActorStorage
//
