coverage:
  range: 60..100
  round: down
  precision: 0

  status:
    project:                   # measuring the overall project coverage
      default:                 # context, you can create multiple ones with custom titles
        enabled: yes
        target: 55%
        threshold: 2%
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error

    patch:
      default:
        enabled: yes
        target: 80%
        branches: null
        threshold: 2%
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error

    changes:
      default:
        enabled: no

comment: false
ignore:
  - "*/testing.go"
