deps:
  cmds:
    - go get -u github.com/whyrusleeping/gx
    - go get -u github.com/whyrusleeping/gx-go
    - gx install
    - go get -u github.com/alecthomas/gometalinter
    - gometalinter --install
    - go get -u github.com/onsi/ginkgo/ginkgo
    - go get -u github.com/onsi/gomega

lint:
  cmds:
    - gometalinter --config=metalint.json ./...

build:
  cmds:
    - go build -ldflags="-X main.Version={{.GIT_COMMIT}}" -v -o go-filecoin .
  sources:
    - ./*.go
    - ./**/*.go
  generates:
    - go-filecoin{{exeExt}}
  method: checksum
  vars:
    GIT_COMMIT:
      sh: git log -n 1 --format=%h

test:
  cmds:
    - ginkgo

cover:
  cmds:
    - ginkgo -cover
