package storagedeal

/*
DO NOT EDIT THIS FILE BY HAND

This file was generated by "github.com/filecoin-project/go-filecoin/internal/pkg/encoding/gen"
*/

import (
	"github.com/filecoin-project/go-filecoin/internal/pkg/encoding"
)

func init() {
	encoding.RegisterIpldCborType(PaymentInfo{})
	encoding.RegisterIpldCborType(Proposal{})
	encoding.RegisterIpldCborType(SignedProposal{})
	encoding.RegisterIpldCborType(Response{})
	encoding.RegisterIpldCborType(SignedResponse{})
	encoding.RegisterIpldCborType(ProofInfo{})
	encoding.RegisterIpldCborType(QueryRequest{})
	encoding.RegisterIpldCborType(Deal{})
}

//
// Encoding/Decoding impls for PaymentInfo
//

//
// Encoding/Decoding impls for Proposal
//

//
// Encoding/Decoding impls for SignedProposal
//

//
// Encoding/Decoding impls for Response
//

//
// Encoding/Decoding impls for SignedResponse
//

//
// Encoding/Decoding impls for ProofInfo
//

//
// Encoding/Decoding impls for QueryRequest
//

//
// Encoding/Decoding impls for Deal
//
