package block
	
/* 
DO NOT EDIT THIS FILE BY HAND

This file was generated by "github.com/filecoin-project/go-filecoin/encoding/gen" 
*/

import (
	"github.com/filecoin-project/go-filecoin/encoding"
)

func init() {
    encoding.RegisterIpldCborType(Block{})
    encoding.RegisterIpldCborType(Ticket{})
}

//
// Encoding/Decoding impls for Block 
// 
	
//
// Encoding/Decoding impls for Ticket 
// 
	