// Code generated by github.com/whyrusleeping/cbor-gen. DO NOT EDIT.

package blocksub

import (
	"fmt"
	"io"

	cid "github.com/ipfs/go-cid"
	cbg "github.com/whyrusleeping/cbor-gen"
	xerrors "golang.org/x/xerrors"
)

var _ = xerrors.Errorf

var lengthBufPayload = []byte{131}

func (t *Payload) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	if _, err := w.Write(lengthBufPayload); err != nil {
		return err
	}

	scratch := make([]byte, 9)

	// t.Header (block.Block) (struct)
	if err := t.Header.MarshalCBOR(w); err != nil {
		return err
	}

	// t.BLSMsgCids ([]cid.Cid) (slice)
	if len(t.BLSMsgCids) > cbg.MaxLength {
		return xerrors.Errorf("Slice value in field t.BLSMsgCids was too long")
	}

	if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajArray, uint64(len(t.BLSMsgCids))); err != nil {
		return err
	}
	for _, v := range t.BLSMsgCids {
		if err := cbg.WriteCidBuf(scratch, w, v); err != nil {
			return xerrors.Errorf("failed writing cid field t.BLSMsgCids: %w", err)
		}
	}

	// t.SECPMsgCids ([]cid.Cid) (slice)
	if len(t.SECPMsgCids) > cbg.MaxLength {
		return xerrors.Errorf("Slice value in field t.SECPMsgCids was too long")
	}

	if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajArray, uint64(len(t.SECPMsgCids))); err != nil {
		return err
	}
	for _, v := range t.SECPMsgCids {
		if err := cbg.WriteCidBuf(scratch, w, v); err != nil {
			return xerrors.Errorf("failed writing cid field t.SECPMsgCids: %w", err)
		}
	}
	return nil
}

func (t *Payload) UnmarshalCBOR(r io.Reader) error {
	*t = Payload{}

	br := cbg.GetPeeker(r)
	scratch := make([]byte, 8)

	maj, extra, err := cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return err
	}
	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 3 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.Header (block.Block) (struct)

	{

		if err := t.Header.UnmarshalCBOR(br); err != nil {
			return xerrors.Errorf("unmarshaling t.Header: %w", err)
		}

	}
	// t.BLSMsgCids ([]cid.Cid) (slice)

	maj, extra, err = cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return err
	}

	if extra > cbg.MaxLength {
		return fmt.Errorf("t.BLSMsgCids: array too large (%d)", extra)
	}

	if maj != cbg.MajArray {
		return fmt.Errorf("expected cbor array")
	}

	if extra > 0 {
		t.BLSMsgCids = make([]cid.Cid, extra)
	}

	for i := 0; i < int(extra); i++ {

		c, err := cbg.ReadCid(br)
		if err != nil {
			return xerrors.Errorf("reading cid field t.BLSMsgCids failed: %w", err)
		}
		t.BLSMsgCids[i] = c
	}

	// t.SECPMsgCids ([]cid.Cid) (slice)

	maj, extra, err = cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return err
	}

	if extra > cbg.MaxLength {
		return fmt.Errorf("t.SECPMsgCids: array too large (%d)", extra)
	}

	if maj != cbg.MajArray {
		return fmt.Errorf("expected cbor array")
	}

	if extra > 0 {
		t.SECPMsgCids = make([]cid.Cid, extra)
	}

	for i := 0; i < int(extra); i++ {

		c, err := cbg.ReadCid(br)
		if err != nil {
			return xerrors.Errorf("reading cid field t.SECPMsgCids failed: %w", err)
		}
		t.SECPMsgCids[i] = c
	}

	return nil
}
