name: Enhancement
description:  Suggest an improvement to an existing venus feature.
labels: [need/triage, kind/enhancement]
body:
- type: checkboxes
  attributes:
    label: Checklist
    description: Please check off the following boxes before continuing to create an improvement suggestion!
    options:
      - label: This is **not** a new feature or an enhancement to the Filecoin protocol. If it is,  please open an [FIP issue](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md).
        required: true
      - label: This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/venus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
        required: true
      - label: This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the venus forum](https://github.com/filecoin-project/venus/discussions/categories/ideas) and select the category as `Ideas`.
        required: true
      - label: I **have** a specific, actionable, and well motivated improvement to propose.
        required: true
- type: checkboxes
  attributes:
    label: Venus component
    description: Please select the venus component you are filing an improvement request for
    options:
      - label: venus daemon - [chain service] chain sync
        required: false
      - label: venus auth - [chain service] authentication
        required: false
      - label: venus messager - [chain service] message management (mpool)
        required: false
      - label: venus gateway - [chain service] gateway
        required: false
      - label: venus miner - [chain service] mining and block production
        required: false
      - label: venus sealer/worker - sealing
        required: false
      - label: venus sealer - proving (WindowPoSt)
        required: false
      - label: venus market - storage deal
        required: false
      - label: venus market - retrieval deal
        required: false
      - label: venus market - data transfer
        required: false
      - label: venus light-weight client
        required: false
      - label: venus JSON-RPC API
        required: false
      - label:  Other
        required: false
- type: textarea
  id: request
  attributes:
    label: Improvement Suggestion
    description: A clear and concise description of what the motivation or the current problem is and what is the suggested improvement?
    placeholder: Ex. Currently venus... However, as a storage provider, I'd like...
  validations:
    required: true
