name: Feature request
description:  Suggest an idea for venus
labels: [need/triage, kind/feature]
body:
- type: checkboxes
  attributes:
    label: Checklist
    description: Please check off the following boxes before continuing to create a new feature request!
    options:
      - label: This is **not** a new feature or an enhancement to the Filecoin protocol. If it is, please open an [FIP issue](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md).
        required: true
      - label: This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the venus forum](https://github.com/filecoin-project/venus/discussions/categories/ideas) and select the category as `Ideas`.
        required: true
      - label: I **have** a specific, actionable, and well motivated feature request to propose.
        required: true
- type: checkboxes
  attributes:
    label: Venus component
    description: Please select the venus component you are filing a new feature request for
    options:
      - label: venus daemon - [chain service] chain sync
        required: false
      - label: venus auth - [chain service] authentication
        required: false
      - label: venus messager - [chain service] message management (mpool)
        required: false
      - label: venus gateway - [chain service] gateway
        required: false
      - label: venus miner - [chain service] mining and block production
        required: false
      - label: venus sealer/worker - sealing
        required: false
      - label: venus sealer - proving (WindowPoSt)
        required: false
      - label: venus market - storage deal
        required: false
      - label: venus market - retrieval deal
        required: false
      - label: venus market - data transfer
        required: false
      - label: venus light-weight client
        required: false
      - label: venus JSON-RPC API
        required: false
      - label:  Other
        required: false
- type: textarea
  id: request
  attributes:
    label: What is the motivation behind this feature request? Is your feature request related to a problem? Please describe.
    description: A clear and concise description of what the motivation or the problem is. 
    placeholder: Ex. I'm always frustrated when [...]
  validations:
    required: true
- type: textarea
  id: solution
  attributes:
    label: Describe the solution you'd like
    description: A clear and concise description of what you want to happen. 
  validations:
    required: true
- type: textarea
  id: alternates
  attributes:
    label: Describe alternatives you've considered
    description: A clear and concise description of any alternative solutions or features you've considered.
  validations:
    required: false
- type: textarea
  id: extra
  attributes:
    label: Additional context
    description: Add any other context, design docs or screenshots about the feature request here.
  validations:
    required: false
