# 注意处理代理和 car 文件的挂载 ,网络类型,扇区大小
# nettype-butterfly
# proxy
# snapshot?err
# size-32Gib

version: '3'
services:
  auth:
    image: tanlang/venus-auth
    ports:
      - 8989:8989
    environment:
      - token=test
    volumes:
      - ./env:/env
    network_mode: "host"
    entrypoint: "/script/compose.sh"


  venus:
    image: tanlang/venus
    ports:
      - 3453:3453
    network_mode: "host"
    volumes:
      - ${snapshot?snapshot.car is needed!}:/snapshot.car
    environment:
      - HTTPS_PROXY=${proxy}
      - nettype=${nettype-butterfly}
    # command: ["--network","${nettype-butterfly}","--import-snapshot","/snapshot.car","--auth-url", "http://127.0.0.1:8989"]
    entrypoint: "/script/compose.sh"
    depends_on:
      - auth


  gateway:
    image: tanlang/venus-gateway
    network_mode: "host"
    ports:
      - 45132:45132
    links:
      - "auth:at"
    # env_file:
      # - ./env/token

    command: ["--listen","/ip4/0.0.0.0/tcp/45132","run","--auth-url", "http://127.0.0.1:8989"]
    depends_on:
      - auth

    

  messager:
    image: tanlang/venus-messager
    network_mode: "host"
    ports:
      - 39812:39812
    links:
      - auth:at
      - venus
      - gateway
    volumes:
      - ./env:/env

    entrypoint: "/script/wait-for-it.sh 127.0.0.1:3453 -t 0  -- /script/compose.sh"
    depends_on:
      - auth
      - venus
      - gateway
  
  miner:
    image: tanlang/venus-miner
    network_mode: "host"
    ports:
      - 12308:12308
    volumes:
      - ./env:/env
    environment:
      - nettype=${nettype-butterfly}
    entrypoint: "/script/wait-for-it.sh 127.0.0.1:3453 -t 0  -- /script/compose.sh"
    # entrypoint: "echo $$nettype"
    depends_on:
      - auth
      - venus
      - gateway

volumes:
  datapass:
