#!/usr/bin/env bash

set -e
set -o pipefail

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

# Go tests
go test -v "./$(basename $DIR)/..." -functional

# Shell Tests
. $DIR/retrieval


