package miner

/*
DO NOT EDIT THIS FILE BY HAND

This file was generated by "github.com/filecoin-project/go-filecoin/internal/pkg/encoding/gen"
*/

import (
	"github.com/filecoin-project/go-filecoin/internal/pkg/encoding"
)

func init() {
	encoding.RegisterIpldCborType(State{})
	encoding.RegisterIpldCborType(Ask{})
}

//
// Encoding/Decoding impls for State
//

//
// Encoding/Decoding impls for Ask
//
