// Code generated by github.com/filecoin-project/tools/gen/api. DO NOT EDIT.

package types

import "github.com/filecoin-project/venus/pkg/types/internal"

//type redefine
type BlockMessagesInfo = internal.BlockMessagesInfo
type FIL = internal.FIL
type Ticket = internal.Ticket
type TipSetKey = internal.TipSetKey
type BlockHeader = internal.BlockHeader
type MessageMaker = internal.MessageMaker
type ReceiptMaker = internal.ReceiptMaker
type Actor = internal.Actor
type VRFPi = internal.VRFPi
type ElectionProof = internal.ElectionProof
type BigInt = internal.BigInt
type BlockMsg = internal.BlockMsg
type Signer = internal.Signer
type BeaconEntry = internal.BeaconEntry
type MockSigner = internal.MockSigner
type HasCid = internal.HasCid
type TipSet = internal.TipSet
type FullBlock = internal.FullBlock
type FullTipSet = internal.FullTipSet
type SignedMessage = internal.SignedMessage
type ChainMsg = internal.ChainMsg
type Message = internal.Message
type UnsignedMessage = internal.UnsignedMessage
type TxMeta = internal.TxMeta
type MessageReceipt = internal.MessageReceipt

//func redefine
var ParseFIL = internal.ParseFIL
var MustParseFIL = internal.MustParseFIL
var NewTipSetKey = internal.NewTipSetKey
var TipSetKeyFromBytes = internal.TipSetKeyFromBytes
var DecodeBlock = internal.DecodeBlock
var NewMessageMaker = internal.NewMessageMaker
var EmptyReceipts = internal.EmptyReceipts
var NewReceiptMaker = internal.NewReceiptMaker
var NewActor = internal.NewActor
var NewInt = internal.NewInt
var FromFil = internal.FromFil
var BigFromBytes = internal.BigFromBytes
var BigFromString = internal.BigFromString
var BigMul = internal.BigMul
var BigDiv = internal.BigDiv
var BigDivFloat = internal.BigDivFloat
var BigMod = internal.BigMod
var BigAdd = internal.BigAdd
var BigSub = internal.BigSub
var BigCmp = internal.BigCmp
var SizeStr = internal.SizeStr
var DeciStr = internal.DeciStr
var NewMockSigner = internal.NewMockSigner
var NewMockSignersAndKeyInfo = internal.NewMockSignersAndKeyInfo
var MustGenerateMixedKeyInfo = internal.MustGenerateMixedKeyInfo
var MustGenerateBLSKeyInfo = internal.MustGenerateBLSKeyInfo
var MustGenerateKeyInfo = internal.MustGenerateKeyInfo
var NewSignedMessageForTestGetter = internal.NewSignedMessageForTestGetter
var CidFromString = internal.CidFromString
var NewCidForTestGetter = internal.NewCidForTestGetter
var NewMessageForTestGetter = internal.NewMessageForTestGetter
var NewMsgs = internal.NewMsgs
var NewSignedMsgs = internal.NewSignedMsgs
var SignMsgs = internal.SignMsgs
var NewMsgsWithAddrs = internal.NewMsgsWithAddrs
var AssertHaveSameCid = internal.AssertHaveSameCid
var AssertCidsEqual = internal.AssertCidsEqual
var RequireIDAddress = internal.RequireIDAddress
var NewForTestGetter = internal.NewForTestGetter
var RequireNewTipSet = internal.RequireNewTipSet
var NewTipSet = internal.NewTipSet
var CidArrsEqual = internal.CidArrsEqual
var NewFullTipSet = internal.NewFullTipSet
var ReverseFullBlock = internal.ReverseFullBlock
var ReverseTipSet = internal.ReverseTipSet
var NewSignedMessage = internal.NewSignedMessage
var NewAttoFIL = internal.NewAttoFIL
var NewAttoFILFromFIL = internal.NewAttoFILFromFIL
var NewAttoFILFromFILString = internal.NewAttoFILFromFILString
var NewAttoFILFromString = internal.NewAttoFILFromString
var NewUnsignedMessage = internal.NewUnsignedMessage
var NewMeteredMessage = internal.NewMeteredMessage
var DecodeMessage = internal.DecodeMessage
var NewGasFeeCap = internal.NewGasFeeCap
var NewGasPremium = internal.NewGasPremium

//value redefine
var ZeroFIL = internal.ZeroFIL
var AttoFil = internal.AttoFil
var FemtoFil = internal.FemtoFil
var PicoFil = internal.PicoFil
var NanoFil = internal.NanoFil
var ErrNotFound = internal.ErrNotFound
var EmptyTSK = internal.EmptyTSK
var ErrActorNotFound = internal.ErrActorNotFound
var BlocksPerEpoch = internal.BlocksPerEpoch
var MaxWinCount = internal.MaxWinCount
var ZeroAddress = internal.ZeroAddress
var TotalFilecoinInt = internal.TotalFilecoinInt
var EmptyInt = internal.EmptyInt
var UndefTipSet = internal.UndefTipSet
var MessageVersion = internal.MessageVersion
var EmptyTokenAmount = internal.EmptyTokenAmount
